version: '3.5'  

services:
    frontend: 
      image: mikkokotola/frontend 
      build: C:\\HY\\frontend-example-docker      
      container_name: frontend
    backend: 
      image: mikkokotola/backend 
      build: C:\\HY\\backend-example-docker
      volumes: 
        - C:\\HY\\backend-example-docker\\logs.txt:/usr/app/logs.txt
      container_name: backend
      environment: 
        - REDIS=redis1
        - DB_USERNAME=zuper
        - DB_PASSWORD=yammeryummer
        - DB_NAME=ztore
        - DB_HOST=postgres1
      depends_on:
        - redis
        - postgres
    redis:
      image: redis:5
      container_name: redis1
      volumes:
      - redisvol:/data
    postgres:
      image: postgres:12
      container_name: postgres1
      restart: unless-stopped
      environment:
        - POSTGRES_USER=zuper
        - POSTGRES_PASSWORD=yammeryummer
        - POSTGRES_DB=ztore
      volumes:
      - postgresdb:/var/lib/postgresql/data
    nginx:
      image: nginx:1.17
      container_name: nginx1
      volumes:
        - C:\\HY\\devops-docker\\Part2\\Ex2.10\\nginx.conf:/etc/nginx/nginx.conf
        - C:\\HY\\devops-docker\\Part2\\Ex2.10\\default_location:/etc/nginx/vhost.d/default_location
      ports:
        - 80:80
      depends_on:
        - backend
        - frontend

volumes:
  redisvol:
  postgresdb: